name: Build and Test Java Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Java version
        run: java -version

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven          

      - name: Maven clean package
        working-directory: java/accounts
        run: mvn clean package -DskipTests

      # - name: Build with Maven
      #   working-directory: java/accounts
      #   run: mvn clean install

      # - name: Run tests
      #   working-directory: java/accounts
      #   run: mvn test



      - name: Build Docker image
        working-directory: java
        run: |
          docker build -t registry.repo.home/levihernandez/accounts-java:latest .                    

      - name: List new image
        run: |
          docker images                    

      - name: Tag image
        run: docker tag registry.repo.home/levihernandez/accounts-java:latest registry.repo.home/levihernandez/accounts-java:latest

      - name: Push Docker image
        run: docker push registry.repo.home/levihernandez/accounts-java:latest
