apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-init
  namespace: cockroachdb
spec:
  template:
    spec:
      containers:
      - name: cockroachdb-init
        image: cockroachdb/cockroach:v24.2.0
        command:
        - "/bin/bash"
        - "-c"
        - |
          cockroach init --insecure --host=cockroachdb-0.cockroachdb          
      restartPolicy: OnFailure
  backoffLimit: 4
