---
apiVersion: v1
kind: Service
metadata:
  name: cockroach-web-public
  namespace: cockroachdb
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: cockroachdb
---
apiVersion: v1
kind: Service
metadata:
  name: cockroach-sql-public
  namespace: cockroachdb
spec:
  type: LoadBalancer
  ports:
  - name: sql
    protocol: TCP
    port: 26257
    targetPort: 26257
  selector:
    app: cockroachdb
