apiVersion: v1
kind: Secret
metadata:
  name: movr-app-secrets
type: Opaque
data:
  # echo -n "postgres://root:''@192.168.86.237:26257/movr?sslmode=disable" | base64
  DB_URI: <db url base64 encoding>
  
