apiVersion: v1
kind: Service
metadata:
  name: dotnet-weather-service
spec:
  selector:
    app: dotnet-weather
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8080
  type: LoadBalancer  # This creates an external LoadBalancer in supported cloud providers
