apiVersion: "datadoghq.com/v1"
kind: "DatadogAgent"
metadata:
  name: "datadog"
spec:
  global:
    clusterName: "movr-cluster"
    tags:
      - "env:crug-demo"
      - "user:jlevi"
      - "user:jhatcer"
      - "presentation:crug"
      - "version:0.0.1"
      - "release:v24.2.2"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
  features:
    apm:
      instrumentation:
        enabled: true
        libVersions:
          java: "1"
          dotnet: "3"
          python: "2"
          js: "5"
          ruby: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
    asm:
      threats:
        enabled: true
      sca:
        enabled: true
      iast:
        enabled: true
    usm:
      enabled: true
    npm:
      enabled: true
    remoteConfiguration:
      enabled: true
    admissionController:
      enabled: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    clusterChecks:
      enabled: true
