apiVersion: apps/v1
kind: Deployment
metadata:
  name: faztpay-api
  labels:
    app: faztpay-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faztpay-api
  template:
    metadata:
      labels:
        app: faztpay-api
    spec:
      containers:
        - name: faztpay-api
          image: levihernandez/faztpay-amd64:1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: faztpay-api-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: faztpay-api-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: faztpay-api-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              valueFrom:
                secretKeyRef:
                  name: faztpay-api-secret
                  key: SPRING_DATASOURCE_DRIVER_CLASS_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: faztpay-api
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: faztpay-api
