apiVersion: v1
kind: Service
metadata:
  name: movr-app-service-lb
spec:
  type: LoadBalancer
  selector:
    app: movr-app
  ports:
    - protocol: TCP
      port: 8087    # External port
      targetPort: 5000  # Internal port in the container
