apiVersion: v1
kind: Secret
metadata:
  name: faztpay-api-secret
type: Opaque
data:
  # echo "postgresql://192.168.86.237:26257/faztpay?application_name=faztpay-api&connect_timeout=15&sslmode=disable" | base64
  SPRING_DATASOURCE_URL: <base64 encoded db url connection>
  SPRING_DATASOURCE_USERNAME: <base64 encoded db username>
  SPRING_DATASOURCE_PASSWORD: <base64 encoded db password>
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver


  
