apiVersion: v1
kind: Service
metadata:
  name: movr-app-service-lb
spec:
  type: LoadBalancer
  selector:
    app: movr-app
  ports:
    - name: web
      protocol: TCP
      port: 80    # External port
      targetPort: 5000  # Internal port in the container
