apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
type: Opaque
data:
  SPRING_DATASOURCE_URL: amRiYzpwb3N0Z3Jlc3FsOi8vMTkyLjE2OC44Ni4yMzU6MjYyNTcvZmF6dHBheT9hcHBsaWNhdGlvbl9uYW1lPWFwcC1hY2NvdW50cy1qYXZhJmNvbm5lY3RfdGltZW91dD0xNSZzc2xtb2RlPWRpc2FibGU=
  SPRING_DATASOURCE_USERNAME: cm9vdA==
  SPRING_DATASOURCE_PASSWORD: cm9vdA==


  
