apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog
---
apiVersion: v1
kind: Namespace
metadata:
  name: movr
---
apiVersion: v1
kind: Namespace
metadata:
  name: faztpay
